"""
GARUDAVYUHA – Engine Specifications & Configuration
Project: Aero Piston Engine Digital Twin (SIH 2026)
Target Engine: Rotax 914 F/UL (Turbocharged 4-Stroke Boxer Engine used in MALE UAVs like Tapas, Rustom, Heron)
Tagline: "PEHLE PREDICT, FIR PROTECT"
"""

ENGINE_CONFIG = {
    "modelName": "Rotax 914 F3 / MALE UAV Certified",
    "displacement": "1,211 cc (73.9 cu in)",
    "cylinderCount": 4,
    "layout": "Horizontally-Opposed Boxer, 4-Stroke",
    "aspiration": "Turbocharged with Automatic Wastegate (TCU)",
    "maxPower": "115 HP @ 5,800 RPM (Takeoff, 5 min max)",
    "continuousPower": "100 HP @ 5,500 RPM",
    "coolingType": "Liquid-Cooled Cylinder Heads / Ram-Air Cylinders",
    "lubricationType": "Dry Sump Forced Lubrication with Trochoid Pump",
    "tbo": 1200,  # Time Between Overhaul (Hours)
    "uavPlatform": "TAPAS-BH-201 / MALE UAV-04",
    "missionId": "OP-VAYUSHAKTI-IX",
    "groundStationId": "GCS-AIRBASE-03",
}

SENSOR_DEFINITIONS = {
    "rpm": {
        "id": "rpm",
        "name": "Engine Speed",
        "label": "RPM",
        "unit": "RPM",
        "normalMin": 4800,
        "normalMax": 5400,
        "cautionMin": 4400,
        "cautionMax": 5600,
        "criticalMin": 3800,
        "criticalMax": 5850,
        "nominal": 5180,
        "description": "Crankshaft rotational speed monitored via inductive pickup",
    },
    "cht": {
        "id": "cht",
        "name": "Cylinder Head Temp",
        "label": "CHT",
        "unit": "°C",
        "normalMin": 110,
        "normalMax": 142,
        "cautionMin": 143,
        "cautionMax": 152,
        "criticalMin": 70,
        "criticalMax": 160,
        "nominal": 136,
        "description": "Peak cylinder head thermal sensor probe (Bank 1 & 2)",
    },
    "egt": {
        "id": "egt",
        "name": "Exhaust Gas Temp",
        "label": "EGT",
        "unit": "°C",
        "normalMin": 680,
        "normalMax": 745,
        "cautionMin": 746,
        "cautionMax": 785,
        "criticalMin": 550,
        "criticalMax": 820,
        "nominal": 715,
        "description": "Turbine inlet exhaust gas temperature thermocouples",
    },
    "oil_press": {
        "id": "oil_press",
        "name": "Oil Pressure",
        "label": "Oil Press",
        "unit": "bar",
        "normalMin": 3.5,
        "normalMax": 5.0,
        "cautionMin": 2.5,
        "cautionMax": 5.5,
        "criticalMin": 1.8,
        "criticalMax": 7.0,
        "nominal": 4.2,
        "description": "Main gallery oil pressure from dry-sump pump",
    },
    "oil_temp": {
        "id": "oil_temp",
        "name": "Oil Temperature",
        "label": "Oil Temp",
        "unit": "°C",
        "normalMin": 85,
        "normalMax": 105,
        "cautionMin": 106,
        "cautionMax": 120,
        "criticalMin": 50,
        "criticalMax": 130,
        "nominal": 96,
        "description": "Lube oil temp before cooler circuit entrance",
    },
    "fuel_flow": {
        "id": "fuel_flow",
        "name": "Fuel Flow",
        "label": "Fuel Flow",
        "unit": "L/h",
        "normalMin": 22.0,
        "normalMax": 27.5,
        "cautionMin": 19.0,
        "cautionMax": 30.0,
        "criticalMin": 15.0,
        "criticalMax": 35.0,
        "nominal": 24.6,
        "description": "Total mass fuel consumption from turbine flowmeter",
    },
    "vibration": {
        "id": "vibration",
        "name": "Vibration RMS",
        "label": "Vibration",
        "unit": "mm/s",
        "normalMin": 0.8,
        "normalMax": 2.2,
        "cautionMin": 2.3,
        "cautionMax": 3.6,
        "criticalMin": 0.0,
        "criticalMax": 6.0,
        "nominal": 1.35,
        "description": "Tri-axial accelerometer on crankcase forward flange",
    },
    "battery_volt": {
        "id": "battery_volt",
        "name": "Avionics Bus Voltage",
        "label": "Battery",
        "unit": "V DC",
        "normalMin": 27.5,
        "normalMax": 28.8,
        "cautionMin": 26.0,
        "cautionMax": 29.5,
        "criticalMin": 23.5,
        "criticalMax": 31.0,
        "nominal": 28.2,
        "description": "Engine-driven 250W alternator & 28V regulated rail",
    },
    "injection_timing": {
        "id": "injection_timing",
        "name": "Injection Timing",
        "label": "Inj Timing",
        "unit": "° BTDC",
        "normalMin": 22.5,
        "normalMax": 25.5,
        "cautionMin": 20.0,
        "cautionMax": 27.0,
        "criticalMin": 16.0,
        "criticalMax": 30.0,
        "nominal": 24.0,
        "description": "Electronic ECU advance angle Before Top Dead Center",
    },
}

ENGINE_SUBSYSTEMS = {
    "fuel_system": {
        "id": "fuel_system",
        "name": "Fuel Injection & Induction",
        "shortName": "Fuel Injectors",
        "position": {"x": -0.10, "y": 0.00, "z": 0.16},
        "cameraOffset": {"x": -0.10, "y": 0.45, "z": 0.35},
        "radius": 0.16,
        "icon": "fa-gas-pump",
        "sensors": ["fuel_flow", "egt", "vibration"],
        "baselineHealth": 98,
        "nominalLifeHrs": 600,
        "spares": "Rotax Genuine Part # 892-451 (Bosch High-Pressure Injector Nozzle)",
        "inspectionProcedure": "Perform ultrasonic cleaning of micro-filters; check solenoid coil resistance (12.2 ± 0.4 Ω); spray atomization pattern test.",
    },
    "cylinders": {
        "id": "cylinders",
        "name": "Cylinder Heads & Combustion Chamber",
        "shortName": "Cylinders & Heads",
        "position": {"x": -0.12, "y": 0.18, "z": 0.02},
        "cameraOffset": {"x": -0.30, "y": 0.65, "z": 0.25},
        "radius": 0.22,
        "icon": "fa-fire",
        "sensors": ["cht", "rpm", "vibration"],
        "baselineHealth": 96,
        "nominalLifeHrs": 1200,
        "spares": "Rotax Cylinder Head Kit # 914-823, Nimonic Exhaust Valves",
        "inspectionProcedure": "Conduct differential cylinder pressure compression check (minimum 72/80 psi); borescope internal combustion dome for carbon hotspots.",
    },
    "turbo_exhaust": {
        "id": "turbo_exhaust",
        "name": "Turbocharger & Wastegate Assembly",
        "shortName": "Turbocharger & Exhaust",
        "position": {"x": -0.32, "y": -0.05, "z": -0.18},
        "cameraOffset": {"x": -0.75, "y": -0.30, "z": -0.10},
        "radius": 0.18,
        "icon": "fa-wind",
        "sensors": ["egt", "rpm", "oil_press"],
        "baselineHealth": 94,
        "nominalLifeHrs": 800,
        "spares": "TCU Wastegate Actuator # 965-442, Inconel Turbine Housing",
        "inspectionProcedure": "Verify servo wastegate butterfly clearance; measure axial & radial shaft play (<0.08 mm); inspect turbine blades for foreign object erosion.",
    },
    "lubrication": {
        "id": "lubrication",
        "name": "Dry-Sump Lubrication & Oil Cooler",
        "shortName": "Oil System",
        "position": {"x": -0.08, "y": 0.00, "z": -0.22},
        "cameraOffset": {"x": 0.10, "y": -0.55, "z": -0.30},
        "radius": 0.20,
        "icon": "fa-oil-can",
        "sensors": ["oil_press", "oil_temp", "vibration"],
        "baselineHealth": 97,
        "nominalLifeHrs": 500,
        "spares": "Rotax High-Flow Spin-on Oil Filter # 825-016, AeroShell Oil Sport Plus 4",
        "inspectionProcedure": "Cut and inspect oil filter pleats for ferrous particles; check pressure regulator spring tension; inspect oil scavenge magnetic chip detector plug.",
    },
    "cooling": {
        "id": "cooling",
        "name": "Liquid Cooling Jackets & Pump",
        "shortName": "Cooling Circuit",
        "position": {"x": 0.02, "y": 0.10, "z": 0.10},
        "cameraOffset": {"x": 0.45, "y": 0.45, "z": 0.30},
        "radius": 0.18,
        "icon": "fa-temperature-low",
        "sensors": ["cht", "oil_temp"],
        "baselineHealth": 95,
        "nominalLifeHrs": 1000,
        "spares": "Mechanical Water Pump Seal Kit # 850-940, Evans Waterless Coolant",
        "inspectionProcedure": "Pressure-test cooling jacket to 1.2 bar; verify thermostat opening at 82°C; check water pump weep hole for glycol crystallization.",
    },
    "ignition": {
        "id": "ignition",
        "name": "Dual Electronic CDI & Ignition Leads",
        "shortName": "Ignition Subsystem",
        "position": {"x": -0.18, "y": 0.12, "z": 0.12},
        "cameraOffset": {"x": -0.40, "y": 0.45, "z": 0.35},
        "radius": 0.17,
        "icon": "fa-bolt",
        "sensors": ["injection_timing", "rpm", "battery_volt"],
        "baselineHealth": 99,
        "nominalLifeHrs": 600,
        "spares": "Dual CDI Electronic Box # 965-385, NGK DCPR8E Spark Plugs",
        "inspectionProcedure": "Inspect high-tension silicon spark leads for insulation breakdown; measure spark gap (0.7 mm); test trigger coil reluctance voltage output.",
    },
    "gearbox_prop": {
        "id": "gearbox_prop",
        "name": "Integrated Reduction Gearbox & Clutch",
        "shortName": "Gearbox & Drive Flange",
        "position": {"x": 0.18, "y": 0.00, "z": 0.05},
        "cameraOffset": {"x": 0.65, "y": 0.00, "z": 0.20},
        "radius": 0.16,
        "icon": "fa-cog",
        "sensors": ["vibration", "rpm"],
        "baselineHealth": 95,
        "nominalLifeHrs": 1200,
        "spares": "Dog Clutch Belleville Spring Pack # 927-573, Gear Ratio 2.43:1",
        "inspectionProcedure": "Measure gearbox backlash on propeller flange (standard 15°–30° free play); inspect overload slipper clutch breakaway torque (600 Nm).",
    },
    "sensor_ecu": {
        "id": "sensor_ecu",
        "name": "ECU / TCU Avionics & Sensor Harness",
        "shortName": "Avionics & Sensors",
        "position": {"x": -0.25, "y": 0.18, "z": -0.05},
        "cameraOffset": {"x": -0.55, "y": 0.45, "z": 0.10},
        "radius": 0.16,
        "icon": "fa-microchip",
        "sensors": ["battery_volt", "injection_timing"],
        "baselineHealth": 99,
        "nominalLifeHrs": 2000,
        "spares": "Rotax TCU Microprocessor Unit # 966-470, Military MIL-DTL-38999 Harness",
        "inspectionProcedure": "Verify CAN bus termination resistance (60 Ω differential); check CAN transceiver error counters; scan diagnostic memory for intermittent bus faults.",
    },
}

FAULT_SCENARIOS = {
    "injector_abnormality": {
        "id": "injector_abnormality",
        "name": "Injector Abnormality",
        "subsystemId": "fuel_system",
        "severity": "CRITICAL",
        "category": "Fuel & Combustion",
        "description": "Micro-clogging or solenoid valve drift in Cylinder #2 high-pressure fuel injector, causing lean air-fuel mixture, localized hot combustion, and rotational torque imbalance.",
        "affectedParameters": {
            "fuel_flow": {"shift": -3.8, "rate": 0.08, "unit": "L/h"},
            "egt": {"shift": 68.0, "rate": 1.4, "unit": "°C"},
            "vibration": {"shift": 1.85, "rate": 0.04, "unit": "mm/s"},
            "rpm": {"shift": -120.0, "rate": 2.2, "unit": "RPM"},
        },
        "shapContributions": [
            {"param": "Fuel Flow Deficit", "weight": 0.42, "direction": "down"},
            {"param": "EGT Elevation", "weight": 0.32, "direction": "up"},
            {"param": "Torque Ripple / Vibration", "weight": 0.18, "direction": "up"},
            {"param": "RPM Fluctuation", "weight": 0.08, "direction": "down"},
        ],
        "aiDiagnosis": "Abnormal fuel metering detected on Bank 1. Flow reduction coupled with sharp EGT elevation and harmonic vibration indicates partial nozzle restriction or solenoid hysteresis.",
        "recommendation": "Switch engine to conservative cruise throttle (4,800 RPM). Abort deep penetration patrol. Inspect/clean fuel injector nozzle and inspect fuel distribution manifold upon RTB.",
        "maintenancePriority": "HIGH PRIORITY",
        "estServiceTime": "2.5 Hours",
    },
    "overheating": {
        "id": "overheating",
        "name": "Thermal Overheating",
        "subsystemId": "cooling",
        "severity": "CRITICAL",
        "category": "Thermal Management",
        "description": "Restricted coolant radiator airflow or expansion valve cavitation during prolonged high-alpha loiter, causing thermal saturation in cylinder heads and lube oil.",
        "affectedParameters": {
            "cht": {"shift": 28.5, "rate": 0.6, "unit": "°C"},
            "oil_temp": {"shift": 22.0, "rate": 0.45, "unit": "°C"},
            "egt": {"shift": 35.0, "rate": 0.7, "unit": "°C"},
            "oil_press": {"shift": -0.65, "rate": 0.015, "unit": "bar"},
        },
        "shapContributions": [
            {"param": "CHT Thermal Excursion", "weight": 0.48, "direction": "up"},
            {"param": "Oil Temp Elevation", "weight": 0.30, "direction": "up"},
            {"param": "Oil Viscosity / Pressure Loss", "weight": 0.14, "direction": "down"},
            {"param": "EGT Cross-coupling", "weight": 0.08, "direction": "up"},
        ],
        "aiDiagnosis": "Thermal equilibrium breached. Cylinder Head Temperature exceeded 155°C limit with secondary oil thermal thinning. Thermal stress risk factor > 0.82.",
        "recommendation": "Increase UAV airspeed to maximize radiator ram-air ventilation; reduce manifold boost pressure. Prepare immediate descent to cooler ambient altitude.",
        "maintenancePriority": "CRITICAL",
        "estServiceTime": "3.0 Hours",
    },
    "lubrication_issue": {
        "id": "lubrication_issue",
        "name": "Lubrication Breakdown",
        "subsystemId": "lubrication",
        "severity": "CRITICAL",
        "category": "Tribology & Fluid Dynamics",
        "description": "Oil scavenger line restriction or pressure relief valve spring degradation causing drop in main gallery pressure, elevated hydrodynamic friction, and bearing temperature spike.",
        "affectedParameters": {
            "oil_press": {"shift": -2.1, "rate": 0.045, "unit": "bar"},
            "oil_temp": {"shift": 27.5, "rate": 0.55, "unit": "°C"},
            "vibration": {"shift": 2.1, "rate": 0.05, "unit": "mm/s"},
            "cht": {"shift": 12.0, "rate": 0.25, "unit": "°C"},
        },
        "shapContributions": [
            {"param": "Oil Gallery Pressure Deficit", "weight": 0.52, "direction": "down"},
            {"param": "Bearing Oil Temp Surge", "weight": 0.26, "direction": "up"},
            {"param": "Crankcase Friction Vibration", "weight": 0.16, "direction": "up"},
            {"param": "CHT Boundary Heat", "weight": 0.06, "direction": "up"},
        ],
        "aiDiagnosis": "Severe oil gallery hydraulic pressure loss (< 2.2 bar). Hydrodynamic lubrication wedge compromised in crankshaft main journals. Immediate friction heating detected.",
        "recommendation": "EXECUTE IMMEDIATE EMERGENCY RTB. Reduce engine power to minimum sustain level. Ground maintenance must inspect scavenge pump and test for ferrous debris.",
        "maintenancePriority": "CRITICAL / GROUND IMMEDIATE",
        "estServiceTime": "4.5 Hours",
    },
    "abnormal_vibration": {
        "id": "abnormal_vibration",
        "name": "Mechanical Bearing Unbalance",
        "subsystemId": "gearbox_prop",
        "severity": "WARNING",
        "category": "Mechanical Dynamics",
        "description": "Excessive high-frequency vibrational energy originating from reduction gearbox dog-clutch spring fatigue or turbocharger turbine shaft dynamic unbalance.",
        "affectedParameters": {
            "vibration": {"shift": 3.9, "rate": 0.09, "unit": "mm/s"},
            "rpm": {"shift": -45.0, "rate": 1.0, "unit": "RPM"},
            "oil_temp": {"shift": 8.5, "rate": 0.15, "unit": "°C"},
        },
        "shapContributions": [
            {"param": "Tri-Axial RMS Vibration", "weight": 0.65, "direction": "up"},
            {"param": "Propeller Flange Harmonics", "weight": 0.22, "direction": "up"},
            {"param": "Gearbox Local Friction", "weight": 0.13, "direction": "up"},
        ],
        "aiDiagnosis": "Broadband vibration excitation centered at 2.43x crankshaft fundamental frequency. Characteristic spectral signature of propeller drive reduction gear lash looseness.",
        "recommendation": "Limit rapid throttle transients to prevent torque shocks. Ground inspection: Measure gearbox backlash (max 30°) and inspect Belleville spring pack tension.",
        "maintenancePriority": "MEDIUM PRIORITY",
        "estServiceTime": "2.0 Hours",
    },
    "sensor_drift": {
        "id": "sensor_drift",
        "name": "CHT Sensor Drift",
        "subsystemId": "sensor_ecu",
        "severity": "ADVISORY",
        "category": "Instrumentation & Telemetry",
        "description": "Thermocouple cold-junction drift or high-impedance harness contact degradation on Cylinder #3 CHT channel, reporting spurious heat while actual thermodynamics remain nominal.",
        "affectedParameters": {
            "cht": {"shift": 32.0, "rate": 0.8, "unit": "°C"},
            "oil_temp": {"shift": 0.8, "rate": 0.02, "unit": "°C"},
            "egt": {"shift": -2.0, "rate": 0.05, "unit": "°C"},
        },
        "shapContributions": [
            {"param": "CHT Probe Residual Disparity", "weight": 0.60, "direction": "up"},
            {"param": "Oil Temp Cross-Validation Inconsistency", "weight": 0.25, "direction": "mismatch"},
            {"param": "EGT Steady State Verification", "weight": 0.15, "direction": "steady"},
        ],
        "aiDiagnosis": "AI Cross-Validation Model flagged instrumentation anomaly. CHT sensor reporting high thermal gradient (+32°C) without corresponding rise in oil temperature or EGT. High confidence sensor drift.",
        "recommendation": "Engine remains safe for operational cruise. Rely on secondary oil temperature and cylinder head backup probe. Schedule avionics harness continuity test at next turnaround.",
        "maintenancePriority": "ADVISORY",
        "estServiceTime": "1.0 Hour",
    },
    "combustion_instability": {
        "id": "combustion_instability",
        "name": "Combustion Instability",
        "subsystemId": "cylinders",
        "severity": "WARNING",
        "category": "Combustion & Ignition",
        "description": "Intermittent spark energy attenuation or fuel atomization inconsistency causing cyclic pressure fluctuations in combustion chambers and fluctuating exhaust pulses.",
        "affectedParameters": {
            "egt": {"shift": 45.0, "rate": 1.1, "unit": "°C", "oscillatory": True},
            "vibration": {"shift": 1.6, "rate": 0.035, "unit": "mm/s", "oscillatory": True},
            "fuel_flow": {"shift": 1.5, "rate": 0.04, "unit": "L/h"},
            "injection_timing": {"shift": -2.2, "rate": 0.05, "unit": "° BTDC"},
        },
        "shapContributions": [
            {"param": "EGT Cyclic Variance", "weight": 0.44, "direction": "oscillate"},
            {"param": "Torsional Vibration Peak", "weight": 0.28, "direction": "up"},
            {"param": "Ignition Timing Jitter", "weight": 0.18, "direction": "jitter"},
            {"param": "Specific Fuel Consumption", "weight": 0.10, "direction": "up"},
        ],
        "aiDiagnosis": "Combustion cycle variability (COV of IMEP) elevated above 8.5%. Multi-cylinder exhaust gas thermal discrepancy indicates erratic ignition discharge or partial misfire.",
        "recommendation": "Switch to redundant secondary CDI ignition circuit. Maintain stable cruising altitude. Inspect spark plugs, electrode gaps, and ignition coil ground upon landing.",
        "maintenancePriority": "HIGH PRIORITY",
        "estServiceTime": "2.0 Hours",
    },
}

DEMO_STEPS = [
    {
        "step": 1,
        "title": "1. Healthy Baseline Cruise",
        "badge": "HEALTHY",
        "subsystem": None,
        "narration": "MALE UAV cruising at 15,000 ft MSL, 5,180 RPM. All thermodynamic telemetry within optimal operational envelope. Engine health 98%, RUL estimated at 48.5 hours.",
        "state": "healthy",
    },
    {
        "step": 2,
        "title": "2. Micro-Vibration Inception",
        "badge": "SUBTLE ANOMALY",
        "subsystem": "fuel_system",
        "narration": "Acoustic and tri-axial vibration sensors capture high-frequency micro-pulsing in the fuel distribution rail. Traditional threshold alarms remain silent as values are within gross limits.",
        "state": "incipient",
    },
    {
        "step": 3,
        "title": "3. AI Residual Anomaly Detection",
        "badge": "AI DETECTION",
        "subsystem": "fuel_system",
        "narration": "GARUDAVYUHA's Autoencoder and Isolation Forest algorithm detects multivariate residual drift. Anomaly score jumps from 0.04 to 0.46.",
        "state": "ai_detected",
    },
    {
        "step": 4,
        "title": "4. Health Index Recalibration",
        "badge": "DEGRADING",
        "subsystem": "fuel_system",
        "narration": "Engine Health Score gracefully begins decay (98% → 87%). System shifts from nominal monitoring into active diagnostic tracking.",
        "state": "degrading",
    },
    {
        "step": 5,
        "title": "5. AI Fault Identification",
        "badge": "PREDICTED FAULT",
        "subsystem": "fuel_system",
        "narration": "Explainable AI (XAI) engine correlates fuel flow deficit (-12%) with elevated exhaust gas temperature (+9%). Identifies 'Injector Abnormality' with 78% confidence.",
        "state": "fault_identified",
    },
    {
        "step": 6,
        "title": "6. 3D Digital Twin Visual Telemetry",
        "badge": "3D AMBER HIGHLIGHT",
        "subsystem": "fuel_system",
        "narration": "Two-way GCS synchronization: The 3D Rotax 914 engine twin rotates smoothly and illuminates the affected Fuel Injector cluster in amber.",
        "state": "3d_amber",
    },
    {
        "step": 7,
        "title": "7. Confidence Surge & Parameter Deviation",
        "badge": "CONFIDENCE: 86%",
        "subsystem": "fuel_system",
        "narration": "Continuous multivariate sampling increases fault classification confidence to 86%. Severe lean mixture starts causing secondary combustion friction.",
        "state": "high_confidence",
    },
    {
        "step": 8,
        "title": "8. Critical Threshold & Pulsing Alert",
        "badge": "CRITICAL ALERT",
        "subsystem": "fuel_system",
        "narration": "Sensor crosses critical envelope. 3D engine twin transitions to glowing, pulsing crimson alert. Audible aerospace tactical chime triggers at GCS console.",
        "state": "critical",
    },
    {
        "step": 9,
        "title": "9. Dynamic RUL Degradation",
        "badge": "RUL COLLAPSE",
        "subsystem": "fuel_system",
        "narration": "Remaining Useful Life projection collapses from 48.5 hours down to 14.2 ± 2.8 hours. Weibull wear hazard rate accelerates exponentially.",
        "state": "rul_drop",
    },
    {
        "step": 10,
        "title": "10. Mission Risk Escalation",
        "badge": "MISSION RISK: HIGH",
        "subsystem": "fuel_system",
        "narration": "Flight envelope reliability drops. Tactical Mission Risk escalates to HIGH. System automatically advises Return-To-Base (RTB) to protect multi-million dollar UAV airframe.",
        "state": "mission_risk",
    },
    {
        "step": 11,
        "title": "11. Ground Maintenance Work Order",
        "badge": "PREDICTIVE ACTION",
        "subsystem": "fuel_system",
        "narration": "Automated work order generated for ground technicians: 'Inspect Cylinder #2 Bosch Injector (Part # 892-451); Ultrasonic nozzle decoke required; Est MTTR: 2.5 hrs.' Mission readiness post-service: 97%.",
        "state": "maintenance_ready",
    },
]

ENVIRONMENT_CONFIG = {
    "standardAmbientTempC": 15.0,
    "currentAmbientTempC": 42.0,
    "altitudeFt": 18200.0,
    "alphaThermalCorrection": 1.0,
    "deltaNoiseThresholdEpsilon": 0.05,
    "vibrationFundamentalFreqHz": 96.6,  # 5,800 RPM / 60
    "nyquistMinSamplingHz": 193.2,
    "telemetrySamplingHz": 500.0,
}

FLEET_NODE_TEMPLATE = {
    "nodeId": "fleet_node_01",
    "engineModel": "Rotax 914 F3 / MALE UAV Certified",
    "isolationForestContamination": 0.01,
    "isolationForestDecisionThreshold": -0.12,
    "weibullShapeBeta": 2.42,
    "weibullScaleEta": 1200.0,
    "maintenanceThresholdPercent": 60.0,
    "adaptiveThermalAlpha": 1.0,
    "chtMaxNominalC": 142.0,
    "egtMaxNominalC": 745.0,
    "oilPressMinBar": 3.5,
    "vibrationMaxNominalMms": 2.2,
}

if __name__ == "__main__":
    print(f"Loaded Rotax 914 Config: {ENGINE_CONFIG['modelName']}")
    print(f"Total Subsystems: {len(ENGINE_SUBSYSTEMS)}")
    print(f"Total Sensors: {len(SENSOR_DEFINITIONS)}")
    print(f"Total Fault Scenarios: {len(FAULT_SCENARIOS)}")
    print(f"Telemetry Sampling Rate: {ENVIRONMENT_CONFIG['telemetrySamplingHz']} Hz (Nyquist Compliant)")

